name: Feature

on:
  push:
    branches:
      - /refs/heads/*
      - !master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: build and release
      run: |
        sh ./.github/scripts/test.sh
        sh ./.github/scripts/build.sh
      env:
        CI: true
        