name: Feature

on:
  push:
    branches-ignore:
    - main

jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: build
      run: |
        set -e
        bash ./.github/scripts/test.bash
        bash ./.github/scripts/build.bash
      env:
        CI: true
        