name: Feature

on:
  push:
    branches-ignore:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: test
      run: |
        set -e
        bash ./.github/scripts/test.bash
      env:
        CI: true
        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: build
      run: |
        set -e
        source ./.github/scripts/version.bash
        bash ./.github/scripts/build.bash
      env:
        CI: true
        