name: Main

on:
  push:
    branches: 
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: build and release
      run: |
        set -e
        source ./.github/scripts/version.sh
        ./.github/scripts/test.sh
        ./.github/scripts/build.sh
        ./.github/scripts/release.sh
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
