name: Main

on:
  push:
    branches: 
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: build and release
      run: |
        set -e
        source ./.github/scripts/version.bash
        bash ./.github/scripts/test.bash
        bash ./.github/scripts/build.bash
        bash ./.github/scripts/release.bash
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
